server:
  port: 8181

spring:
  liquibase:
    changeLog: classpath:/db/master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/localdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Ajusta automaticamente as tabelas (ou use 'validate' se jรก estiver criado)
    show-sql: true  # Exibe as queries no console