server:
  port: 8181

spring:
  datasource:
    url: jdbc:h2:~/test_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  liquibase:
    changeLog: classpath:/db/master.xml