version: '3.8'

services:
  postgres:
    image: postgres:alpine  # Usa a versão mais leve do PostgreSQL
    container_name: postgres-container
    restart: always  # Reinicia automaticamente em caso de falha
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: localdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Volume para persistência dos dados

volumes:
  pgdata:  # Define o volume persistente
